### ISSUE TITLE
static files not found on pages with trailing slash

### ISSUE THREAD

**Issue by conradreisch** [app-generator/django-adminator#10]
Dear developer,
after setting up an app url with a traling slash, e.g. `path('stores/', views.stores, name='stores'),`, the static files cannot be found. It seems that django is searching those files in the subdirectory stores, e.g. `GET /stores/static/assets/fonts/e23a7dcaefbde4e74e263247aa42ecd7.ttf HTTP/1.1" 404`.
If I change the path from "stores/" to "stores.html" everything works fine. 
I'm not sure if this is a bug or just a misconfiguration on my end. Any help would be appreciated!
BR, Conrad

**Comment by conradreisch** [comment]
Actually, the issue applies for all paths in a subdirectory. Even if I add `path('homes/index.html', views.index, name='home')` to the app/urls.py and call "http://127.0.0.1:8000/homes/index.html" the static content is not found.

**Comment by conradreisch** [comment]
I was not able to find and fix the issue. It seems to be somewhere in the bundled java script. However, there is a workaround.

1. add `re_path(r"^(.*)static/assets/(?P<url>.*)$", views.static_redirect, name='static_redirect'),` to the urlpatterns in app/urls.py

2. add the following function to app/views.py
```
def static_redirect(request, url):
    response = HttpResponse(status=302)
    response['Location'] = '/static/assets/' + url
    return response
```

This is redirecting the broken links to cure the symptoms. However, a real fix would be very appreciated.

**Comment by app-generator** [comment]
Patch in the latest version - Now the UI uses a `Gulp managed` project. 
[Adminator](https://github.com/app-generator/adminator) **v2.0.3**
