### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by olivierpons** [app-generator/django-adminator#2]
Hi,

Each time, in the menu on your left, you open a submenu it works, but each time you re-click on the menu to close it you'll get tons of `Error: <circle> attribute cx: Expected length, "NaN".`

![image](https://user-images.githubusercontent.com/1741596/89883585-a0722a00-dbc8-11ea-8264-f6b9353c9cbc.png)

**Comment by ToTheMax** [comment]
Same over here!
Happens when you click / zoom in on the world-map

**Comment by app-generator** [comment]
Patch in the latest version - Now the UI uses a `Gulp managed` project. 
[Adminator](https://github.com/app-generator/adminator) **v2.0.3**
