### ISSUE TITLE
Issue with woff and ttf static files

### ISSUE THREAD

**Issue by GrazianoC** [app-generator/django-adminator#3]
Hi, calling the url http://127.0.0.1:8000/user/graziano/ I find it difficult to view the page correctly as the static files related to the "adminator" fonts are mapped incorrectly:

ex. GET /user/graziano/static/assets/fonts/e23a7dcaefbde4e74e263247aa42ecd7.ttf HTTP / 1.1 "404

This happens with the ttf and woff files.

As you can see, the system adds the url relative to the route (user / graziano) to the relative path "static / assets / fonts / e23a7dcaefbde4e74e263247aa42ecd7.ttf"

The html templates are all at the same level.

Can you give me a suggestion?

**Comment by app-generator** [comment]
Patch in the latest version - Now the UI uses a `Gulp managed` project. 
[Adminator](https://github.com/app-generator/adminator) **v2.0.3**
