### ISSUE TITLE
After starting the local server i cant register a new user

### ISSUE THREAD

**Issue by ambroyer** [app-generator/django-adminator#9]
Hi, I've tried running a local instance of the adminator on my pc and the app seems to launch as expected after i go through the README instructions. But when i try to register anew user i get "Form invalid" message

**Comment by ambroyer** [comment]
ive tried some more steps and it seems that the error handling is not working correctly since when i changed the length of the password it accepted it. Before i didnt get any validations on the form
I used
test
test@gmail.com
Azerty12

**Comment by app-generator** [comment]
Hello, 

It was a small bug on the registration form regarding the errors for the `password confirmation field.

Please use the latest revision (fresh install) or `git pull` at the root of the project.

P.S. Django requires a strong password when creating users.
